### ISSUE TITLE
Namespace for the soil health knowledge graph and SoilWise project

### ISSUE THREAD

**Issue by wbcbugfree** [soilwise-he/soil-health-knowledge-graph#12]
In constructing the soil health knowledge graph, new concepts need to be defined, although it is already trying to reuse concepts that already exist as much as possible. Therefore, a unique namespace is needed to assign a URI to these new concepts.
Previously, I was using:
```turtle
@prefix ex: <http://example.org/> .
```
, which is not a good practice. Because ultimately we need to publish and open source this knowledge graph.
For now, I'm using:
```turtle
@prefix she: <http://soilwise-he.github.io/soil-health#> .
```
but whether this is a permanent solution is still up for discussion.

**Comment by pvgenuchten** [comment]
GitHub.io or w3id.org are both good from persistence perspective, let’s use Thursday to set it up

**Comment by roblokers** [comment]
w3id sounds like a logical choice to me...

**Comment by wbcbugfree** [comment]
The namespace is [online](http://soilwise-he.github.io/soil-health/).

**Comment by pvgenuchten** [comment]
We can still add a w3id facade on top of it if there is interest

**Comment by wbcbugfree** [comment]
The prefix "ns0" should be replaced to something more formal...
